# Site settings
author: Savannah Correll
title: Learn.co Blog
header-img: img/home-bg.png
email: sgcorrell@gmail.com
copyright_name: Savannah Correll
description: > # this means to ignore newlines until "baseurl:"
  Blog for reflection during the Learn.co curriculum
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  vulcanism

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
